#!/usr/bin/env bash

# Build a temp file string for use with the configuration

python ./scripts/install-agent.py \
    -s applications/MarketAgents/VAVAgent \
    -i platform.vav4\
    --config config/tcc/building1/vav4-config \
    --tag vav \
    --start \
    --force