#!/usr/bin/env bash

# Build a temp file string for use with the configuration
python ./scripts/install-agent.py \
    -s applications/energyplusagent \
    -i platform.actuator \
    --tag eplus \
    --config config/energyplus/building1/ep_building1.config \
    --start \
    --force


